import {consumeUsage} from './lib/usage.js';
import {validateCatalog} from './lib/catalog-integrity.js';
import {loadEnvironment,groqComplete} from './lib/groq.js';
import {catalog,categories,getTemplate,facets} from './lib/catalog.js';
import {templateHTML,projectFiles} from './lib/templates.js';
import {zip} from './lib/zip.js';
import http from 'node:http';
import {createDatabase} from './lib/database.js';
import {randomBytes,scryptSync,timingSafeEqual,createHash} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=path.dirname(fileURLToPath(import.meta.url));
loadEnvironment(path.join(root,'.env'));
const db=await createDatabase({root});
await db.exec(`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT UNIQUE,name TEXT,password TEXT,salt TEXT,locale TEXT DEFAULT 'en',theme TEXT DEFAULT 'light');
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id TEXT REFERENCES users(id),expires INTEGER);
CREATE TABLE IF NOT EXISTS projects(id TEXT PRIMARY KEY,user_id TEXT REFERENCES users(id),name TEXT,prompt TEXT,type TEXT,html TEXT,favorite INTEGER DEFAULT 0,updated TEXT);
CREATE TABLE IF NOT EXISTS versions(id TEXT PRIMARY KEY,project_id TEXT REFERENCES projects(id) ON DELETE CASCADE,html TEXT,prompt TEXT,created TEXT);
CREATE TABLE IF NOT EXISTS usage_limits(bucket TEXT PRIMARY KEY,count INTEGER DEFAULT 0);`);
if(!(await db.prepare('PRAGMA table_info(users)').all()).some(c=>c.name==='theme'))await db.exec("ALTER TABLE users ADD COLUMN theme TEXT DEFAULT 'light'");
validateCatalog(catalog);
const id=()=>randomBytes(16).toString('hex');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function generate(prompt,type,color='#635bff'){
 const title=prompt.replace(/^(build|create|make|design)\s+(a|an)?\s*/i,'').slice(0,80);
 const interactive=type==='web app'?`<section class="card"><h2>Your focus workspace</h2><p>Tasks are kept in this page for the current visit.</p><form id="taskform"><label>New task<input id="task" required maxlength="200"></label><button>Add task</button></form><ul id="tasks"></ul><p id="taskcount" role="status">0 tasks remaining</p><h3>Focus timer</h3><p id="timer" role="timer">25:00</p><button id="start">Start / pause</button> <button id="reset">Reset</button></section><script>let count=0,seconds=1500,ticking=false;const display=()=>document.getElementById('timer').textContent=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0');setInterval(()=>{if(ticking&&seconds>0){seconds--;display();if(!seconds)ticking=false}},1000);document.getElementById('start').onclick=()=>ticking=!ticking;document.getElementById('reset').onclick=()=>{ticking=false;seconds=1500;display()};document.getElementById('taskform').onsubmit=ev=>{ev.preventDefault();const li=document.createElement('li'),b=document.createElement('button');li.style.margin='12px 0';b.textContent=document.getElementById('task').value;b.setAttribute('aria-label','Complete '+b.textContent);b.onclick=()=>{li.remove();count--;document.getElementById('taskcount').textContent=count+' tasks remaining'};li.append(b);document.getElementById('tasks').append(li);count++;document.getElementById('taskcount').textContent=count+' tasks remaining';ev.target.reset()};</script>`:type==='storefront'?`<section class="card"><h2>Your selection</h2><p>Interactive cart demonstration. Payments are not connected.</p><p id="cart" role="status">0 items · $0.00</p><button onclick="items=0;document.getElementById('cart').textContent='0 items · $0.00'">Clear selection</button></section><script>let items=0;document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{items++;document.getElementById('cart').textContent=items+' items · '+new Intl.NumberFormat('en',{style:'currency',currency:'USD'}).format(items*29);b.textContent='Added ✓';setTimeout(()=>b.textContent='Add to selection · $29',900)});</script>`:'<section class="card"><h2>Questions, answered.</h2><details><summary>How do we get started?</summary><p>Tell us about your goals using the contact form below.</p></details><details><summary>Can we work together internationally?</summary><p>We welcome conversations from around the world.</p></details></section>';
 return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>*{box-sizing:border-box}body{margin:0;font:16px system-ui;color:#172022;background:#f7f9f5}header,main,footer{max-width:1100px;margin:auto;padding:28px}nav{display:flex;justify-content:space-between;align-items:center}a{color:inherit;text-decoration:none}h1{font-size:clamp(40px,7vw,80px);line-height:1.04;letter-spacing:-3px;max-width:850px}p{line-height:1.7;color:#5f6968}button,.cta{border:0;background:${color};color:white;padding:16px 24px;border-radius:10px;display:inline-block;cursor:pointer}.eyebrow{color:${color};font-weight:700;text-transform:uppercase;letter-spacing:2px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;margin:60px 0}.card{border:1px solid #dce3da;border-radius:16px;padding:28px;background:white}input,textarea{display:block;width:100%;padding:14px;margin:12px 0;border:1px solid #cbd5c5;border-radius:8px}footer{border-top:1px solid #dce3da}@media(max-width:650px){.grid{grid-template-columns:1fr}h1{letter-spacing:-1px}}</style><header><nav><strong>✳ ${esc(title.slice(0,24))}</strong><a href="#contact">Let's talk ↗</a></nav></header><main><span class="eyebrow">Built for what's next</span><h1>${esc(title)}</h1><p>${esc(prompt)}</p><a class="cta" href="#features">Explore ${esc(type)} →</a><section class="grid" id="features">${['Thoughtfully designed','Made for everyone','A better experience'].map((x,i)=>`<article class="card"><span class="eyebrow">0${i+1}</span><h2>${x}</h2><p>Discover a considered approach that brings clarity, quality, and purpose to every detail.</p>${type==='storefront'?'<button data-add>Add to selection · $29</button>':''}</article>`).join('')}</section>${interactive}<section id="contact"><h2>Start a conversation</h2><p>This exported template has a local demonstration form. Connect a form service to receive submissions.</p><form onsubmit="event.preventDefault();document.getElementById('status').textContent='Thank you! This demo has recorded your submission in this page only.';this.reset()"><label>Your email<input type="email" required></label><label>Your message<textarea required></textarea></label><button>Send message</button><p id="status" role="status"></p></form></section></main><footer>© ${new Date().getFullYear()} ${esc(title.slice(0,40))} · Designed with Bebin Dev Studio</footer></html>`;
}

const server=http.createServer(async(req,res)=>{
 const send=(status,data)=>{res.writeHead(status,{'Content-Type':'application/json'});res.end(JSON.stringify(data));};
 res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');res.setHeader('X-Frame-Options','DENY');
 const url=new URL(req.url,'http://localhost');
 try{
 res.setHeader('Cache-Control','no-store');
 if(url.pathname==='/api/health'&&req.method==='GET'){await db.prepare('SELECT 1 AS ready').get();return send(200,{ok:true,database:db.kind});}
 if(!url.pathname.startsWith('/api/')){const files={'/':'index.html','/app.js':'app.js','/style.css':'style.css','/theme-init.js':'theme-init.js','/catalog-ui.js':'catalog-ui.js','/coding-scene.js':'coding-scene.js','/product-ui.js':'product-ui.js','/login-ui.js':'login-ui.js','/login-ui.css':'login-ui.css','/product-ui.css':'product-ui.css','/coding-scene.css':'coding-scene.css','/logo.png':'logo.png','/coding-process.mp4':'coding-process.mp4','/coding-process-poster.jpg':'coding-process-poster.jpg'};const shot=url.pathname.match(/^\/screenshots\/([a-z0-9-]+)\.jpg$/);const file=files[url.pathname]||(shot&&getTemplate(shot[1])?'screenshots/'+shot[1]+'.jpg':null);if(!file)return send(404,{error:'Not found'});res.setHeader('Content-Type',file.endsWith('mp4')?'video/mp4':file.endsWith('css')?'text/css':file.endsWith('js')?'text/javascript':file.endsWith('png')?'image/png':file.endsWith('jpg')?'image/jpeg':'text/html');res.setHeader('Content-Security-Policy',"default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self'; frame-src 'self' about:; connect-src 'self'; img-src 'self' data:; media-src 'self'");const asset=readFileSync(path.join(root,'public',file));if(file.endsWith('mp4')){res.setHeader('Cache-Control','public, max-age=86400');res.setHeader('Accept-Ranges','bytes');if(req.headers.range){const range=req.headers.range.match(/^bytes=(\d+)-(\d*)$/);if(!range)return res.writeHead(416,{'Content-Range':'bytes */'+asset.length}),res.end();const start=Number(range[1]),end=Math.min(range[2]?Number(range[2]):asset.length-1,asset.length-1);if(start>end||start>=asset.length)return res.writeHead(416,{'Content-Range':'bytes */'+asset.length}),res.end();res.writeHead(206,{'Content-Range':'bytes '+start+'-'+end+'/'+asset.length,'Content-Length':end-start+1});return res.end(asset.subarray(start,end+1));}}res.setHeader('Content-Length',asset.length);return res.end(asset);}
 if(req.method!=='GET' && req.headers.origin && req.headers.origin!==`http://${req.headers.host}` && req.headers.origin!==`https://${req.headers.host}`)return send(403,{error:'Invalid origin'});
 let body={};if(req.method!=='GET'){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>1000000)return send(413,{error:'Request too large'});}try{body=JSON.parse(raw||'{}');}catch{return send(400,{error:'Invalid JSON'});}}
 if(['/api/register','/api/login'].includes(url.pathname)){
 if(req.method!=='POST')return send(405,{error:'Use POST'});
 const clientAddress=process.env.VERCEL?String(req.headers['x-forwarded-for']||req.socket.remoteAddress).split(',')[0].trim():req.socket.remoteAddress;await consumeUsage(db,'auth:'+createHash('sha256').update(clientAddress||'unknown').digest('hex'),20,60000);
 const email=String(body.email||'').trim().toLowerCase(),password=String(body.password||'');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||password.length<10||password.length>128)return send(400,{error:'Use a valid email and a password with 10–128 characters.'});
 let user=await db.prepare('SELECT * FROM users WHERE email=?').get(email);
 if(url.pathname==='/api/register'){if(user)return send(409,{error:'This email is already registered.'});const salt=id(),uid=id();await db.prepare('INSERT INTO users(id,email,name,password,salt) VALUES(?,?,?,?,?)').run(uid,email,String(body.name||'Creator').slice(0,80),scryptSync(password,salt,64).toString('hex'),salt);user=await db.prepare('SELECT * FROM users WHERE id=?').get(uid);}else if(!user||!timingSafeEqual(Buffer.from(user.password,'hex'),scryptSync(password,user.salt,64)))return send(401,{error:'Email or password is incorrect.'});
 const token=id()+id();await db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(createHash('sha256').update(token).digest('hex'),user.id,Date.now()+604800000);res.setHeader('Set-Cookie',`session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=604800${process.env.NODE_ENV==='production'?'; Secure':''}`);return send(200,{user:{name:user.name,email:user.email,locale:user.locale,theme:user.theme}});
 }
 const token=(req.headers.cookie||'').match(/(?:^|; )session=([a-f0-9]+)/)?.[1]||'';const hash=createHash('sha256').update(token).digest('hex');const user=await db.prepare('SELECT users.* FROM sessions JOIN users ON users.id=sessions.user_id WHERE token=? AND expires>?').get(hash,Date.now());
 if(!user)return send(401,{error:'Please sign in.'});
 if(req.method==='POST'&&process.env.GROQ_API_KEY&&(['/api/enhance','/api/ai/test'].includes(url.pathname)||(url.pathname==='/api/generate'&&body.mode==='ai'))){await consumeUsage(db,'ai-user:'+user.id,40,86400000);await consumeUsage(db,'ai-global',200,86400000);}

 if(url.pathname==='/api/me')return send(200,{user:{name:user.name,email:user.email,locale:user.locale,theme:user.theme},aiAvailable:!!process.env.GROQ_API_KEY,aiProvider:"Groq",aiModel:process.env.GROQ_MODEL||"openai/gpt-oss-20b"});
 if(url.pathname==='/api/logout'&&req.method==='POST'){await db.prepare('DELETE FROM sessions WHERE token=?').run(hash);res.setHeader('Set-Cookie','session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0'+(process.env.NODE_ENV==='production'?'; Secure':''));return send(200,{ok:true});}
 if(url.pathname==='/api/settings'&&req.method==='PATCH'){if(body.locale!==undefined&&!['en','es','fr','hi','ar'].includes(body.locale))return send(400,{error:'Unsupported language'});if(body.theme!==undefined&&!['light','dark','aurora'].includes(body.theme))return send(400,{error:'Unsupported theme'});await db.prepare('UPDATE users SET locale=?,theme=? WHERE id=?').run(body.locale||user.locale,body.theme||user.theme,user.id);return send(200,{ok:true});}
 if(url.pathname==='/api/ai/test'&&req.method==='POST'){const result=await groqComplete('Return the words: Bebin integration ready',{enhance:true});return send(200,{ok:!!result,provider:'Groq',model:process.env.GROQ_MODEL||'openai/gpt-oss-20b'});}
 if(url.pathname==='/api/enhance'&&req.method==='POST'){const prompt=String(body.prompt||'').trim();if(prompt.length<12||prompt.length>4000)return send(400,{error:'Use a brief of 12–4000 characters'});const enhanced=process.env.GROQ_API_KEY?await groqComplete(prompt,{enhance:true}):prompt+' Use a responsive layout, accessible contrast, clear navigation, working local interactions, and a refined visual hierarchy.';return send(200,{prompt:enhanced.slice(0,4000),engine:process.env.GROQ_API_KEY?'Groq':'Local'});}
 if(url.pathname==='/api/templates'&&req.method==='GET'){
 const query=String(url.searchParams.get('q')||'').toLowerCase().slice(0,200),industry=url.searchParams.get('industry')||url.searchParams.get('category')||'',style=url.searchParams.get('style')||'',type=url.searchParams.get('type')||'',framework=url.searchParams.get('framework')||'',feature=url.searchParams.get('feature')||'';const page=Math.max(1,Math.min(100000,Number(url.searchParams.get('page'))||1)),limit=12;
 const matches=catalog.filter(t=>(!industry||t.category===industry)&&(!style||t.style===style)&&(!type||t.type===type)&&(!framework||t.framework===framework)&&(!feature||t.features.includes(feature))&&query.split(/\s+/).every(term=>(t.name+' '+t.description+' '+t.tags.join(' ')).toLowerCase().includes(term)));
 return send(200,{items:matches.slice((page-1)*limit,page*limit),total:matches.length,catalogTotal:catalog.length,page,pages:Math.ceil(matches.length/limit),categories,facets});}
 const tm=url.pathname.match(/^\/api\/templates\/([a-z0-9-]+)\/(preview|download|use|info)$/);if(tm){const t=getTemplate(tm[1]);if(!t)return send(404,{error:'Template not found'});if(tm[2]==='info'&&req.method==='GET')return send(200,t);if(tm[2]==='preview'&&req.method==='GET'){res.removeHeader('X-Frame-Options');res.setHeader('Content-Type','text/html');res.setHeader('Content-Security-Policy',"default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src data:; connect-src 'none'; form-action 'none'; frame-ancestors 'self'; sandbox allow-scripts allow-forms");return res.end(templateHTML(t));}if(tm[2]==='download'&&req.method==='GET'){res.setHeader('Content-Type','application/zip');res.setHeader('Content-Disposition','attachment; filename="'+t.id+'.zip"');return res.end(zip(projectFiles(t)));}if(tm[2]==='use'&&req.method==='POST'){const pid=id(),now=new Date().toISOString(),html=templateHTML(t);await db.batch([{sql:'INSERT INTO projects(id,user_id,name,prompt,type,html,updated) VALUES(?,?,?,?,?,?,?)',args:[pid,user.id,t.brand,t.description,t.type,html,now]},{sql:'INSERT INTO versions VALUES(?,?,?,?,?)',args:[id(),pid,html,t.description,now]}]);return send(200,{id:pid});}return send(405,{error:'Unsupported method'});}
 if(url.pathname==='/api/projects'&&req.method==='GET')return send(200,await db.prepare('SELECT id,name,prompt,type,favorite,updated FROM projects WHERE user_id=? ORDER BY updated DESC').all(user.id));
 if(url.pathname==='/api/generate'&&req.method==='POST'){
 const prompt=String(body.prompt||'').trim();if(prompt.length<12||prompt.length>4000)return send(400,{error:'Describe your project in 12–4,000 characters.'});const type=['web app','landing page','storefront'].includes(body.type)?body.type:'landing page';let html=generate(prompt,type,/^#[0-9a-f]{6}$/i.test(body.color||'')?body.color:undefined);
 if(body.mode==='ai'){html=await groqComplete(`${type}: ${prompt}`);}
 const existing=body.projectId?await db.prepare('SELECT * FROM projects WHERE id=? AND user_id=?').get(body.projectId,user.id):null;if(body.projectId&&!existing)return send(404,{error:'Project not found'});const pid=existing?.id||id(),now=new Date().toISOString();await db.batch([existing?{sql:'UPDATE projects SET prompt=?,html=?,updated=?,name=?,type=? WHERE id=?',args:[prompt,html,now,String(body.name||existing.name).slice(0,80),type,pid]}:{sql:'INSERT INTO projects(id,user_id,name,prompt,type,html,updated) VALUES(?,?,?,?,?,?,?)',args:[pid,user.id,String(body.name||prompt).slice(0,80),prompt,type,html,now]},{sql:'INSERT INTO versions VALUES(?,?,?,?,?)',args:[id(),pid,html,prompt,now]}]);return send(200,{id:pid,html});}
 const match=url.pathname.match(/^\/api\/projects\/([a-f0-9]+)(?:\/(versions|restore|export|preview|source|duplicate))?$/);if(match){const p=await db.prepare('SELECT * FROM projects WHERE id=? AND user_id=?').get(match[1],user.id);if(!p)return send(404,{error:'Project not found'});if(match[2]==='source'&&req.method==='PUT'){const html=String(body.html||'');if(html.length<50||html.length>500000)return send(400,{error:'HTML must be 50–500,000 characters'});const now=new Date().toISOString();await db.batch([{sql:'UPDATE projects SET html=?,updated=? WHERE id=?',args:[html,now,p.id]},{sql:'INSERT INTO versions VALUES(?,?,?,?,?)',args:[id(),p.id,html,p.prompt,now]}]);return send(200,{ok:true});}if(match[2]==='duplicate'&&req.method==='POST'){const pid=id(),now=new Date().toISOString();await db.batch([{sql:'INSERT INTO projects(id,user_id,name,prompt,type,html,updated) VALUES(?,?,?,?,?,?,?)',args:[pid,user.id,p.name+' (copy)',p.prompt,p.type,p.html,now]},{sql:'INSERT INTO versions VALUES(?,?,?,?,?)',args:[id(),pid,p.html,p.prompt,now]}]);return send(200,{id:pid});}if(match[2]==='versions')return send(200,await db.prepare('SELECT id,prompt,created FROM versions WHERE project_id=? ORDER BY created DESC').all(p.id));if(match[2]==='restore'&&req.method==='POST'){const v=await db.prepare('SELECT * FROM versions WHERE id=? AND project_id=?').get(body.versionId,p.id);if(!v)return send(404,{error:'Version not found'});await db.prepare('UPDATE projects SET html=?,prompt=?,updated=? WHERE id=?').run(v.html,v.prompt,new Date().toISOString(),p.id);return send(200,{ok:true});}if(match[2]==='preview'){res.removeHeader('X-Frame-Options');res.setHeader('Content-Type','text/html');res.setHeader('Cache-Control','no-store');res.setHeader('Content-Security-Policy',"default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src data:; form-action 'none'; connect-src 'none'; frame-ancestors 'self'; sandbox allow-scripts allow-forms");return res.end(p.html);}if(match[2]==='export'){res.setHeader('Content-Type','text/html');res.setHeader('Content-Disposition','attachment; filename="bebin-project.html"');return res.end(p.html);}if(req.method==='DELETE'){await db.batch([{sql:'DELETE FROM versions WHERE project_id=?',args:[p.id]},{sql:'DELETE FROM projects WHERE id=?',args:[p.id]}]);return send(200,{ok:true});}if(req.method==='PATCH'){const name=String(body.name??p.name).trim();if(!name)return send(400,{error:'A project name is required'});await db.prepare('UPDATE projects SET name=?,favorite=? WHERE id=?').run(name.slice(0,80),body.favorite===undefined?p.favorite:body.favorite?1:0,p.id);return send(200,{ok:true});}return send(200,p);}
 return send(404,{error:'Not found'});
 }catch(e){console.error('Request failed:',e.status||500);send(e.status||500,{error:e.status?e.message:'Something went wrong. Please try again.'});}
});
export default server;
if(!process.env.VERCEL)server.listen(Number(process.env.PORT||3000),process.env.HOST||'127.0.0.1',()=>console.log(`Bebin Dev Studio running at http://127.0.0.1:${process.env.PORT||3000}`));






