import test from 'node:test';
import {spawnSync} from 'node:child_process';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {createDatabase} from '../lib/database.js';
import {createAuth,verifyGoogleIdentity} from '../lib/auth.js';
import {generateKeyPair,SignJWT} from 'jose';
const req=cookie=>({headers:{cookie:cookie||''},socket:{remoteAddress:'127.0.0.1'}});
const response=()=>{const headers={};return {getHeader:k=>headers[k],setHeader:(k,v)=>headers[k]=v,headers};};
const cookie=(res,name='session')=>res.headers['Set-Cookie'].find(v=>v.startsWith(name+'=')).split(';')[0];
async function fixture(driver='sqlite'){const root=process.env.AUTH_TEST_ROOT||mkdtempSync(path.join(tmpdir(),'bebin-auth-')),db=await createDatabase({root,env:{DATABASE_DRIVER:driver}});await db.exec("CREATE TABLE users(id TEXT PRIMARY KEY,email TEXT UNIQUE,name TEXT,password TEXT,salt TEXT,locale TEXT DEFAULT 'en',theme TEXT DEFAULT 'light');CREATE TABLE sessions(token TEXT PRIMARY KEY,user_id TEXT,expires INTEGER);CREATE TABLE usage_limits(bucket TEXT PRIMARY KEY,count INTEGER);");let time=Date.now(),messages=[];const env={APP_BASE_URL:'http://127.0.0.1:3016',EMAIL_FROM:'Studio <signin@example.com>',GOOGLE_CLIENT_ID:'test-client',GOOGLE_CLIENT_SECRET:'test-secret'};const auth=await createAuth({db,env,mailer:message=>messages.push(message),now:()=>time});return {db,env,auth,messages,advance:ms=>time+=ms,close:()=>{db.close();if(!process.env.AUTH_TEST_ROOT)rmSync(root,{recursive:true,force:true,maxRetries:10,retryDelay:100});}};}
for(const driver of ['sqlite','libsql'])test('single-use email links and persistent sessions: '+driver,async()=>{if(driver==='libsql'&&!process.env.AUTH_TEST_ROOT){const root=mkdtempSync(path.join(tmpdir(),'bebin-auth-'));try{const child=spawnSync(process.execPath,['--test','--test-name-pattern=libsql','tests/auth.test.js'],{env:{...process.env,AUTH_TEST_ROOT:root},encoding:'utf8'});assert.equal(child.status,0,child.stdout+child.stderr);}finally{rmSync(root,{recursive:true,force:true});}return;}const f=await fixture(driver);try{const res=response();const result=await f.auth.requestEmail(req(),res,'Creator@example.com');assert.equal(result.ok,true);assert.equal(JSON.stringify(result).includes('token'),false);const token=f.messages[0].text.match(/#token=([\w-]+)/)[1];assert.equal((await f.auth.emailInfo(req(cookie(res,'magic_intent')),token)).automatic,true);await assert.rejects(f.auth.confirmEmail(req(),response(),token,false),{status:409});const signed=response();const user=await f.auth.confirmEmail(req(cookie(res,'magic_intent')),signed,token,false);assert.equal(user.email,'creator@example.com');assert.match(signed.headers['Set-Cookie'][0],/HttpOnly; SameSite=Lax; Path=\/; Max-Age=34560000/);const jar=cookie(signed);assert.equal((await f.auth.authenticated(req(jar),response())).id,user.id);const restored=await createAuth({db:f.db,env:f.env});assert.equal((await restored.authenticated(req(jar),response())).id,user.id);await assert.rejects(f.auth.confirmEmail(req(),response(),token,true),{status:400});f.advance(2*86400000);const renewed=response();assert.ok(await f.auth.authenticated(req(jar),renewed));assert.ok(renewed.headers['Set-Cookie']);await f.auth.logout(req(jar),response());assert.equal(await f.auth.authenticated(req(jar),response()),null);const next=response();await f.auth.requestEmail(req(),next,'other@example.com');const expired=f.messages.at(-1).text.match(/#token=([\w-]+)/)[1];f.advance(901000);await assert.rejects(f.auth.confirmEmail(req(),response(),expired,true),{status:400});}finally{f.close();}});
test('Google identity validates signature, audience, nonce and verified email',async()=>{const {privateKey,publicKey}=await generateKeyPair('RS256');const sign=payload=>new SignJWT({email:'creator@gmail.com',email_verified:true,nonce:'nonce',...payload}).setProtectedHeader({alg:'RS256'}).setIssuer('https://accounts.google.com').setAudience('client').setSubject('subject').setIssuedAt().setExpirationTime('5m').sign(privateKey);const options={clientId:'client',nonce:'nonce',keys:publicKey};assert.equal((await verifyGoogleIdentity(await sign({}),options)).sub,'subject');await assert.rejects(verifyGoogleIdentity(await sign({nonce:'wrong'}),options));await assert.rejects(verifyGoogleIdentity(await sign({email_verified:false}),options));await assert.rejects(verifyGoogleIdentity(await sign({}),{...options,clientId:'wrong'}));});
test('Google OAuth state and PKCE are checked and existing accounts preserved',async()=>{const f=await fixture();try{let exchange;const auth=await createAuth({db:f.db,env:f.env,fetcher:async(url,options)=>{exchange=options.body;return {ok:true,json:async()=>({id_token:'test'})};},verifyIdentity:async()=>({sub:'google-user',email:'creator@gmail.com',name:'Creator'})});const res=response(),url=new URL(await auth.googleStart(req(),res));assert.equal(url.searchParams.get('code_challenge_method'),'S256');const callback=new URL('http://localhost/api/auth/google/callback?code=code&state='+url.searchParams.get('state'));await assert.rejects(auth.googleCallback(req(),response(),callback));const signed=response();const result=await auth.googleCallback(req(cookie(res,'oauth_state')),signed,callback);assert.equal(result.user.email,'creator@gmail.com');assert.equal(exchange.get('redirect_uri'),f.env.APP_BASE_URL+'/api/auth/google/callback');assert.ok(exchange.get('code_verifier'));await assert.rejects(auth.googleCallback(req(cookie(res,'oauth_state')),response(),callback));}finally{f.close();}});
test('failed delivery removes challenge; absent providers fail clearly',async()=>{const f=await fixture();try{const none=await createAuth({db:f.db,env:{}});assert.deepEqual(none.config(),{google:false,email:false});await assert.rejects(none.requestEmail(req(),response(),'a@example.com'),{status:503});const broken=await createAuth({db:f.db,env:f.env,mailer:()=>{throw Error('delivery failed');}});await assert.rejects(broken.requestEmail(req(),response(),'a@example.com'));assert.equal((await f.db.prepare('SELECT count(*) AS n FROM auth_challenges').get()).n,0);}finally{f.close();}});
test('production cookies are secure and concurrent email use allows one winner',async()=>{const f=await fixture();try{const auth=await createAuth({db:f.db,env:{...f.env,NODE_ENV:'production',APP_BASE_URL:'https://bebin-dev.vercel.app'},mailer:message=>f.messages.push(message)});const request=response();await auth.requestEmail(req(),request,'secure@example.com');const token=f.messages[0].text.match(/#token=([\w-]+)/)[1];const first=response(),second=response();const results=await Promise.allSettled([auth.confirmEmail(req(),first,token,true),auth.confirmEmail(req(),second,token,true)]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);const signed=first.headers['Set-Cookie']?first:second;assert.match(cookie(signed,'__Host-session'),/^__Host-session=[a-f0-9]{64}$/);assert.match(signed.headers['Set-Cookie'].find(x=>x.startsWith('__Host-session=')),/; Secure$/);const stored=await f.db.prepare('SELECT token FROM sessions').get();assert.notEqual(stored.token,cookie(signed,'__Host-session').split('=')[1]);}finally{f.close();}});
test('email delivery is rate limited without revealing account existence',async()=>{const f=await fixture();try{for(let i=0;i<3;i++)await f.auth.requestEmail(req(),response(),'limited@example.com');await assert.rejects(f.auth.requestEmail(req(),response(),'limited@example.com'),{status:429});assert.equal(f.messages.length,3);}finally{f.close();}});
