import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {fullstackProjectFiles} from '../lib/fullstack-project.js';
import {zip} from '../lib/zip.js';
const dir=mkdtempSync(path.join(tmpdir(),'atlas-test-'));let proc,cookie='',other='';const base='http://127.0.0.1:3099';
async function call(route,method='GET',body,session=cookie){const r=await fetch(base+'/api'+route,{method,headers:{'Content-Type':'application/json',Cookie:session},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};}
before(async()=>{proc=spawn(process.execPath,['server.js'],{env:{...process.env,AUTH_LEGACY_PASSWORD:'true',PORT:'3099',DATA_DIR:dir,GROQ_API_KEY:''},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{proc.stdout.once('data',resolve);proc.once('error',reject);proc.once('exit',code=>reject(Error('Server exited '+code)));});});
after(()=>{proc.kill();setTimeout(()=>rmSync(dir,{recursive:true,force:true}),500).unref();});
test('coding video supports browser byte ranges without exposing arbitrary files',async()=>{
 const full=await fetch(base+'/coding-process.mp4');assert.equal(full.status,200);assert.equal(full.headers.get('content-type'),'video/mp4');const bytes=new Uint8Array(await full.arrayBuffer());
 const range=await fetch(base+'/coding-process.mp4',{headers:{Range:'bytes=0-31'}});assert.equal(range.status,206);assert.equal(range.headers.get('content-range'),`bytes 0-31/${bytes.length}`);assert.deepEqual(new Uint8Array(await range.arrayBuffer()),bytes.slice(0,32));
 assert.equal((await fetch(base+'/coding-process.mp4',{headers:{Range:'bytes=99999999-'}})).status,416);
 assert.equal((await fetch(base+'/coding-process-poster.jpg')).status,200);
});
test('complete lifecycle, validation, account isolation, versions and export',async()=>{
 assert.equal((await call('/projects')).status,401);
 assert.equal((await call('/register','POST',{email:'bad',password:'short'})).status,400);
 const reg=await call('/register','POST',{email:'creator@example.com',password:'LongPassword123!',name:'Creator'});assert.equal(reg.status,200);cookie=reg.cookie;
 assert.match(cookie,/session=/);
 assert.equal((await call('/login','POST',{email:'creator@example.com',password:'WrongPassword123'})).status,401);
 assert.equal((await call('/generate','POST',{prompt:'short'})).status,400);
 const created=await call('/generate','POST',{prompt:'Create a global coffee storefront with a product collection',type:'storefront',name:'Coffee'});assert.equal(created.status,200);assert.match(created.data.html,/Add to cart/);const pid=created.data.id;
 const second=await call('/register','POST',{email:'other@example.com',password:'LongPassword123!'},'');other=second.cookie;assert.equal((await call('/projects/'+pid,'GET',null,other)).status,404);assert.equal((await call('/projects/'+pid,'DELETE',null,other)).status,404);
 assert.equal((await call('/projects/'+pid,'PATCH',{name:'Coffee worldwide',favorite:true})).status,200);
 let list=await call('/projects');assert.equal(list.data.length,1);assert.equal(list.data[0].favorite,1);assert.equal(list.data[0].name,'Coffee worldwide');
 await call('/generate','POST',{projectId:pid,prompt:'Refine this coffee website with a sustainability story',type:'storefront'});
 const versions=await call('/projects/'+pid+'/versions');assert.equal(versions.data.length,2);
 await call('/projects/'+pid+'/restore','POST',{versionId:versions.data[1].id});assert.match((await call('/projects/'+pid)).data.prompt,/global coffee/);
 assert.equal((await call('/settings','PATCH',{locale:'ar'})).status,200);assert.equal((await call('/me')).data.user.locale,'ar');assert.equal((await call('/settings','PATCH',{locale:'invalid'})).status,400);
 assert.equal((await call('/settings','PATCH',{theme:'aurora'})).status,200);assert.equal((await call('/me')).data.user.theme,'aurora');assert.equal((await call('/settings','PATCH',{theme:'neon'})).status,400);
 const catalog=await call('/templates');assert.equal(catalog.data.total,20);assert.equal(catalog.data.items.length,12);assert.equal(catalog.data.pages,2);
 assert.equal((await call('/templates?industry=finance&type=dashboard&framework=vanilla&style=dashboard&feature=expense%20tracker')).data.items[0].id,'ledger');
 assert.equal((await call('/templates?industry=finance&feature=cart')).data.total,0);
 assert.equal((await call('/templates?category=education')).data.total,1);assert.equal((await call('/templates?q=cart')).data.total,1);assert.equal((await call('/templates?style=dashboard')).data.total,2);assert.equal((await call('/templates?q=doesnotexist')).data.total,0);
 const catalogPreview=await fetch(base+'/api/templates/horizon/preview',{headers:{Cookie:cookie}});assert.equal(catalogPreview.status,200);assert.match(await catalogPreview.text(),/Horizon Learning/);
 const catalogZip=await fetch(base+'/api/templates/horizon/download',{headers:{Cookie:cookie}});assert.equal(catalogZip.status,200);assert.equal(new Uint8Array(await catalogZip.arrayBuffer())[0],0x50);
 const fromBrief=await call('/templates/horizon/use','POST');assert.equal(fromBrief.status,200);assert.equal(fromBrief.data.backend,true);assert.ok((await call('/projects/'+fromBrief.data.id)).data.app_spec);assert.equal((await call('/projects/'+fromBrief.data.id+'/runtime','POST',{path:'/api/config',method:'GET'})).data.preview,true);await call('/projects/'+fromBrief.data.id,'DELETE');
 assert.equal((await fetch(base+'/.env')).status,404);assert.equal((await fetch(base+'/lib/groq.js')).status,404);
 const preview=await fetch(base+'/api/projects/'+pid+'/preview',{headers:{Cookie:cookie}});assert.equal(preview.status,200);assert.match(preview.headers.get('content-security-policy'),/connect-src 'none'/);assert.match(preview.headers.get('content-security-policy'),/sandbox allow-scripts/);
 assert.equal((await call('/projects/'+pid+'/source','PUT',{html:'short'})).status,400);
 const original=(await call('/projects/'+pid)).data.html;assert.equal((await call('/projects/'+pid+'/source','PUT',{html:original.replace('Your cart','Your coffee cart')})).status,200);assert.match((await call('/projects/'+pid)).data.html,/Your coffee cart/);
 assert.equal((await call('/projects/'+pid+'/source','PUT',{html:original},other)).status,404);
 const copy=await call('/projects/'+pid+'/duplicate','POST');assert.equal(copy.status,200);assert.match((await call('/projects/'+copy.data.id)).data.name,/copy/);await call('/projects/'+copy.data.id,'DELETE');
 const download=await fetch(base+'/api/projects/'+pid+'/export',{headers:{Cookie:cookie}});assert.equal(download.status,200);assert.match(download.headers.get('content-disposition'),/attachment/);assert.match(await download.text(),/<!doctype html>/);
 const sourceZip=await fetch(base+'/api/projects/'+pid+'/download',{headers:{Cookie:cookie}});assert.equal(sourceZip.status,200);assert.equal(sourceZip.headers.get('content-type'),'application/zip');assert.match(sourceZip.headers.get('content-disposition'),/attachment/);assert.deepEqual(Buffer.from(await sourceZip.arrayBuffer()),zip(fullstackProjectFiles((await call('/projects/'+pid)).data)));
 assert.equal((await fetch(base+'/api/projects/'+pid+'/download',{headers:{Cookie:other}})).status,404);assert.equal((await fetch(base+'/api/projects/'+pid+'/download')).status,401);assert.equal((await call('/projects/'+pid+'/download','DELETE')).status,405);assert.equal((await call('/projects/'+pid)).status,200);
 const runtimePath='/projects/'+pid+'/runtime';
 const runtimeCall=(path,method='GET',body,session=cookie)=>call(runtimePath,'POST',{path,method,body},session);
 assert.equal((await runtimeCall('/api/config')).data.preview,true);
 assert.equal((await runtimeCall('/api/health','GET',null,other)).status,404);
 const previewAccount=await runtimeCall('/api/auth/register','POST',{email:'preview@example.test',password:'PreviewPassword123!',name:'Preview operator'});assert.equal(previewAccount.status,200);assert.equal(previewAccount.data.user.role,'admin');assert.equal(previewAccount.data.sessionToken,undefined);
 const previewProduct=await runtimeCall('/api/records/products','POST',{name:'Coffee beans',description:'Fresh roast',price:29,category:'Coffee'});assert.equal(previewProduct.status,201);
 assert.equal((await runtimeCall('/api/products')).data.items[0].name,'Coffee beans');
 assert.equal((await runtimeCall('/api/auth/me')).data.user.email,'preview@example.test');
 assert.equal((await runtimeCall('/api/contact','POST',{name:'Buyer',email:'buyer@example.test',message:'Interested in wholesale'})).status,201);
 assert.equal((await runtimeCall('/api/records/submissions')).data.total,1);
 assert.equal((await call('/generate','POST',{projectId:pid,prompt:'Create a CRM contacts management application',type:'web app'})).status,409);
 assert.equal((await call('/generate','POST',{prompt:'Create a storefront with Stripe payment processing',type:'storefront'})).status,422);
 const previewOrder=await runtimeCall('/api/orders','POST',{items:[{id:previewProduct.data.id,quantity:2}],delivery:'Test street address'});assert.equal(previewOrder.data.totalMinor,5800);
 await runtimeCall('/api/auth/logout','POST',{});assert.equal((await runtimeCall('/api/auth/me')).data.user,null);
 assert.equal((await runtimeCall('/api/auth/login','POST',{email:'preview@example.test',password:'PreviewPassword123!'})).status,200);
 const origin=await fetch(base+'/api/projects/'+pid,{method:'DELETE',headers:{Cookie:cookie,Origin:'https://evil.example'}});assert.equal(origin.status,403);
 const escaped=await call('/generate','POST',{prompt:'Create a website containing <script>alert(1)</script>'});assert.match(escaped.data.html,/\\u003cscript>/);
 assert.equal((await call('/generate','POST',{prompt:'Create a professional landing page',mode:'ai'})).status,400);
 assert.equal((await call('/projects/'+pid,'DELETE')).status,200);assert.equal((await call('/projects/'+pid)).status,404);
 assert.equal((await call('/logout','POST')).status,200);assert.equal((await call('/me')).status,401);
 const login=await call('/login','POST',{email:'creator@example.com',password:'LongPassword123!'});assert.equal(login.status,200);cookie=login.cookie;assert.equal((await call('/projects')).data.length,1);
});
test('account and project data survive a server restart',async()=>{
 const exit=new Promise(resolve=>proc.once('exit',resolve));proc.kill();await exit;
 proc=spawn(process.execPath,['server.js'],{env:{...process.env,AUTH_LEGACY_PASSWORD:'true',PORT:'3099',DATA_DIR:dir,GROQ_API_KEY:''},stdio:['ignore','pipe','pipe']});
 await new Promise((resolve,reject)=>{proc.stdout.once('data',resolve);proc.once('error',reject);});
 assert.equal((await call('/me')).status,200);
 assert.equal((await call('/projects')).data.length,1);
 const login=await call('/login','POST',{email:'creator@example.com',password:'LongPassword123!'});assert.equal(login.status,200);
});
