// Native controls work with pointer, touch and keyboard. State stays on this device.
const q=s=>document.querySelector(s);
const readState=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(config.id+':'+key))??fallback;}catch{return fallback;}};
const saveState=(key,value)=>{try{localStorage.setItem(config.id+':'+key,JSON.stringify(value));}catch{}};
function records(){const filter=q('[data-filter]')?.value||'all',search=q('[data-record-search]')?.value.toLowerCase()||'';document.querySelectorAll('[data-record]').forEach(el=>el.hidden=(filter!=='all'&&el.dataset.group!==filter)||!el.textContent.toLowerCase().includes(search));}
q('[data-filter]')?.addEventListener('change',records);q('[data-record-search]')?.addEventListener('input',records);
let bag=readState('bag',[]);function renderBag(){if(!q('#bag-items'))return;q('#bag-items').replaceChildren();for(const item of bag){const li=document.createElement('li');li.textContent=item.name+' · '+item.qty+' × $'+item.price;const remove=document.createElement('button');remove.textContent='Remove one';remove.onclick=()=>{item.qty--;bag=bag.filter(x=>x.qty>0);saveState('bag',bag);renderBag();};li.append(remove);q('#bag-items').append(li);}q('#bag-total').textContent=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(bag.reduce((n,x)=>n+x.price*x.qty,0));}
document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>{const item=bag.find(x=>x.name===b.dataset.buy);if(item)item.qty++;else bag.push({name:b.dataset.buy,price:Number(b.dataset.price),qty:1});saveState('bag',bag);renderBag();announce('Added to your collection');});q('[data-clear-bag]')?.addEventListener('click',()=>{bag=[];saveState('bag',bag);renderBag();});renderBag();
let bookmarks=readState('bookmarks',[]);document.querySelectorAll('[data-bookmark]').forEach(b=>{const update=()=>{b.textContent=bookmarks.includes(b.dataset.bookmark)?'Saved ✓':'Save';b.setAttribute('aria-pressed',String(bookmarks.includes(b.dataset.bookmark)));};update();b.onclick=()=>{bookmarks=bookmarks.includes(b.dataset.bookmark)?bookmarks.filter(x=>x!==b.dataset.bookmark):[...bookmarks,b.dataset.bookmark];saveState('bookmarks',bookmarks);update();};});
document.querySelectorAll('[data-story]').forEach(b=>b.onclick=()=>{q('#story-title').textContent=b.dataset.story;q('#story-dialog').showModal();});q('[data-close-story]')?.addEventListener('click',()=>q('#story-dialog').close());
let expenses=readState('expenses',[]);function renderExpenses(){if(!q('#expense-list'))return;q('#expense-list').replaceChildren();for(const x of expenses){const li=document.createElement('li');li.textContent=x.name+' — $'+x.amount.toFixed(2);const b=document.createElement('button');b.textContent='Remove';b.onclick=()=>{expenses=expenses.filter(e=>e.id!==x.id);saveState('expenses',expenses);renderExpenses();};li.append(b);q('#expense-list').append(li);}q('#expense-total').textContent='$'+expenses.reduce((n,x)=>n+x.amount,0).toFixed(2);}
q('#expense-form')?.addEventListener('submit',e=>{e.preventDefault();const amount=Number(q('#expense-amount').value);if(!Number.isFinite(amount)||amount<=0)return;expenses.push({id:crypto.randomUUID(),name:q('#expense-name').value.trim(),amount});saveState('expenses',expenses);renderExpenses();e.target.reset();});renderExpenses();
q('#contribution')?.addEventListener('input',()=>q('#savings-result').textContent=Number(q('#contribution').value)>0?Math.ceil(12000/Number(q('#contribution').value))+' months to reach $12,000':'Enter a positive contribution');
let posts=readState('posts',[{id:'welcome',text:'Welcome to the commons. What are you making today?',likes:0}]);function renderPosts(){if(!q('#post-list'))return;q('#post-list').replaceChildren();for(const p of [...posts].sort((a,b)=>q('#feed-order')?.value==='popular'?b.likes-a.likes:0)){const article=document.createElement('article'),text=document.createElement('p'),b=document.createElement('button');text.textContent=p.text;b.textContent='♥ '+p.likes;b.onclick=()=>{p.likes++;saveState('posts',posts);renderPosts();};article.append(text,b);q('#post-list').append(article);}}
q('#post-form')?.addEventListener('submit',e=>{e.preventDefault();const text=q('#post-text').value.trim();if(!text)return;posts.unshift({id:crypto.randomUUID(),text,likes:0});saveState('posts',posts);renderPosts();e.target.reset();});renderPosts();q('#feed-order')?.addEventListener('change',renderPosts);
let kanban=readState('kanban',[{id:'first',text:'Map the launch milestones',lane:'Backlog'}]);function renderKanban(){if(!q('[data-lane]'))return;document.querySelectorAll('[data-lane]').forEach(e=>e.replaceChildren());for(const task of kanban){const card=document.createElement('article'),p=document.createElement('p'),select=document.createElement('select'),remove=document.createElement('button');p.textContent=task.text;select.setAttribute('aria-label','Move '+task.text);for(const lane of ['Backlog','In progress','Done']){const o=document.createElement('option');o.textContent=lane;select.append(o);}select.value=task.lane;select.onchange=()=>{task.lane=select.value;saveState('kanban',kanban);renderKanban();};remove.textContent='Remove';remove.onclick=()=>{kanban=kanban.filter(x=>x.id!==task.id);saveState('kanban',kanban);renderKanban();};card.append(p,select,remove);q('[data-lane="'+task.lane+'"]').append(card);}q('#kanban-progress').textContent=kanban.filter(x=>x.lane==='Done').length+' / '+kanban.length+' complete';}
q('#kanban-form')?.addEventListener('submit',e=>{e.preventDefault();const text=q('#kanban-input').value.trim();if(!text)return;kanban.push({id:crypto.randomUUID(),text,lane:'Backlog'});saveState('kanban',kanban);renderKanban();e.target.reset();});renderKanban();
let habits=readState('habits',[{id:'walk',text:'Take a short walk',dates:[]}]);const day=new Date().toLocaleDateString('en-CA');function renderHabits(){if(!q('#habit-list'))return;q('#today-label').textContent=new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric'}).format(new Date());q('#habit-list').replaceChildren();for(const h of habits){const a=document.createElement('article'),label=document.createElement('label'),c=document.createElement('input');c.type='checkbox';c.checked=h.dates.includes(day);c.onchange=()=>{h.dates=c.checked?[...h.dates,day]:h.dates.filter(d=>d!==day);saveState('habits',habits);renderHabits();};let streak=0;for(let i=0;i<365;i++){const date=new Date();date.setDate(date.getDate()-i);if(h.dates.includes(date.toLocaleDateString('en-CA')))streak++;else break;}label.append(c,document.createTextNode(h.text+' · '+streak+' day streak'));const b=document.createElement('button');b.textContent='Remove';b.onclick=()=>{habits=habits.filter(x=>x.id!==h.id);saveState('habits',habits);renderHabits();};a.append(label,b);q('#habit-list').append(a);}q('#habit-progress').textContent=habits.filter(x=>x.dates.includes(day)).length+' of '+habits.length+' completed today';}
q('#habit-form')?.addEventListener('submit',e=>{e.preventDefault();const text=q('#habit-input').value.trim();if(!text)return;habits.push({id:crypto.randomUUID(),text,dates:[]});saveState('habits',habits);renderHabits();e.target.reset();});renderHabits();
document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{q('#assistant-prompt').value=b.dataset.preset;q('#assistant-prompt').focus();});
q('#seat-count')?.addEventListener('input',()=>q('#seat-price').textContent=q('#seat-count').value+' seats · $'+Number(q('#seat-count').value)*19+' / month');
function energy(){if(q('#energy-result'))q('#energy-result').textContent=(Math.max(0,Number(q('#roof-area').value))*0.2*4).toFixed(1)+' kWh / day, estimated';}q('#roof-area')?.addEventListener('input',energy);energy();
