import http from 'node:http';
import {readFileSync,mkdirSync,existsSync} from 'node:fs';
import {createHash,randomBytes,scryptSync,timingSafeEqual} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
if(existsSync(path.join(root,'.env')))for(const line of readFileSync(path.join(root,'.env'),'utf8').split(/\r?\n/)){const m=line.match(/^([A-Z_]+)=(.*)$/);if(m&&process.env[m[1]]===undefined)process.env[m[1]]=m[2].trim().replace(/^['"]|['"]$/g,'');}
const dataDir=process.env.DATA_DIR||path.join(root,'.template-data');mkdirSync(dataDir,{recursive:true});const db=new DatabaseSync(path.join(dataDir,'project.sqlite'));
db.exec('CREATE TABLE IF NOT EXISTS contacts(id TEXT PRIMARY KEY,email TEXT,message TEXT,kind TEXT,created TEXT); CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT UNIQUE,name TEXT,password TEXT,salt TEXT); CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id TEXT,expires INTEGER);');
const hash=t=>createHash('sha256').update(t).digest('hex');const id=()=>randomBytes(24).toString('hex');const limits=new Map();
const server=http.createServer(async(req,res)=>{
  res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','same-origin');
  const send=(status,body)=>{res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(body));};
  const url=new URL(req.url,'http://localhost');
  try{
    if(!url.pathname.startsWith('/api/')){const name={'/':'index.html','/styles.css':'styles.css','/app.js':'app.js','/assets/brand.svg':'assets/brand.svg'}[url.pathname]||(/^\/assets\/[a-z-]+\.svg$/.test(url.pathname)?url.pathname.slice(1):null);if(!name)return send(404,{error:'Not found'});res.setHeader('Content-Type',name.endsWith('css')?'text/css':name.endsWith('js')?'text/javascript':name.endsWith('svg')?'image/svg+xml':'text/html');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; base-uri 'none'; form-action 'self'");return res.end(readFileSync(path.join(root,'public',name)));}
    if(req.method!=='GET'&&req.headers.origin&&req.headers.origin!==`http://${req.headers.host}`&&req.headers.origin!==`https://${req.headers.host}`)return send(403,{error:'Invalid origin'});
    let body={};if(req.method!=='GET'){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>20000)return send(413,{error:'Request too large'});}try{body=JSON.parse(raw||'{}');}catch{return send(400,{error:'Invalid JSON'});}}
    if(req.method==='POST'){const key=req.socket.remoteAddress,now=Date.now(),rate=limits.get(key)||{time:now,count:0};if(now-rate.time>60000){rate.time=now;rate.count=0;}limits.set(key,rate);if(++rate.count>40)return send(429,{error:'Please wait a minute before retrying.'});}
    if(url.pathname==='/api/contact'&&req.method==='POST'){if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(body.email||'')))return send(400,{error:'A valid email is required'});const message=String(body.message||JSON.stringify(Object.fromEntries(Object.entries(body).filter(([key])=>key!=='email')))||'Submission request').trim().slice(0,4000);if(!message)return send(400,{error:'A message is required'});const contactId=id();db.prepare('INSERT INTO contacts VALUES(?,?,?,?,?)').run(contactId,String(body.email),message,String(body.kind||'contact').slice(0,60),new Date().toISOString());return send(201,{id:contactId});}
    if(['/api/register','/api/login'].includes(url.pathname)&&req.method==='POST'){const email=String(body.email||'').trim().toLowerCase(),password=String(body.password||'');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||password.length<10||password.length>128)return send(400,{error:'Use a valid email and a password of 10–128 characters'});let user=db.prepare('SELECT * FROM users WHERE email=?').get(email);if(url.pathname==='/api/register'){if(user)return send(409,{error:'Account already exists'});const salt=id();user={id:id(),email,name:String(body.name||'Creator').slice(0,80),salt,password:scryptSync(password,salt,64).toString('hex')};db.prepare('INSERT INTO users VALUES(?,?,?,?,?)').run(user.id,email,user.name,user.password,salt);}else if(!user||!timingSafeEqual(Buffer.from(user.password,'hex'),scryptSync(password,user.salt,64)))return send(401,{error:'Incorrect credentials'});const token=id();db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(hash(token),user.id,Date.now()+86400000);res.setHeader('Set-Cookie',`session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=86400${process.env.NODE_ENV==='production'?'; Secure':''}`);return send(200,{id:user.id,name:user.name});}
    const token=(req.headers.cookie||'').match(/(?:^|; )session=([a-f0-9]+)/)?.[1];const user=db.prepare('SELECT users.* FROM sessions JOIN users ON users.id=sessions.user_id WHERE token=? AND expires>?').get(hash(token||''),Date.now());
    if(url.pathname==='/api/me')return user?send(200,{id:user.id,name:user.name}):send(401,{error:'Sign in required'});
    if(url.pathname==='/api/logout'&&req.method==='POST'){db.prepare('DELETE FROM sessions WHERE token=?').run(hash(token||''));res.setHeader('Set-Cookie','session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');return send(200,{ok:true});}
    if(url.pathname==='/api/assistant'&&req.method==='POST'){if(!process.env.GROQ_API_KEY)return send(503,{error:'Set GROQ_API_KEY in the server .env file to enable AI'});const prompt=String(body.prompt||'').trim();if(prompt.length<4||prompt.length>4000)return send(400,{error:'Use a prompt of 4–4000 characters'});const response=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${process.env.GROQ_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.GROQ_MODEL||'openai/gpt-oss-20b',messages:[{role:'user',content:prompt}],reasoning_effort:"low",max_completion_tokens:4000}),signal:AbortSignal.timeout(60000)});if(!response.ok)return send(502,{error:'AI provider unavailable. Check the server key and quota.'});const data=await response.json();return send(200,{text:data.choices?.[0]?.message?.content||'No response'});}
    send(404,{error:'Not found'});
  }catch{send(500,{error:'Request failed'});}
});
server.listen(Number(process.env.PORT||4173),'127.0.0.1',()=>console.log('Project running on http://127.0.0.1:'+Number(process.env.PORT||4173)));
