const config=JSON.parse(document.querySelector('#template-config').textContent);
const $=s=>document.querySelector(s);
function announce(message){$('#notice').textContent=message;}
let storageKey='bebin-template-'+config.id;
let state;try{state=JSON.parse(localStorage.getItem(storageKey))||{};}catch{state={};}
const persist=()=>{try{localStorage.setItem(storageKey,JSON.stringify(state));}catch{}};
$('#menu-toggle').onclick=()=>{const open=$('#navigation').classList.toggle('open');$('#menu-toggle').setAttribute('aria-expanded',String(open));};
document.querySelectorAll('#navigation a').forEach(a=>a.onclick=()=>{$('#navigation').classList.remove('open');$('#menu-toggle').setAttribute('aria-expanded','false');});
const search=$('#item-search'),filter=$('#item-filter');
function filterCards(){const q=(search?.value||'').toLowerCase(),category=filter?.value||'all';document.querySelectorAll('[data-item]').forEach(card=>card.hidden=!card.textContent.toLowerCase().includes(q)||(category!=='all'&&card.dataset.group!==category));const remaining=[...document.querySelectorAll('[data-item]')].filter(x=>!x.hidden).length;const count=$('#result-count');if(count)count.textContent=remaining+' results';}
search?.addEventListener('input',filterCards);filter?.addEventListener('change',filterCards);
state.cart??={};
function renderCart(){if(!$('#cart-list'))return;$('#cart-list').replaceChildren();let quantity=0,total=0;for(const [key,n]of Object.entries(state.cart)){const product=config.items.find(i=>i.id===key);if(!product||n<1)continue;quantity+=n;total+=product.price*n;const li=document.createElement('li'),text=document.createElement('span');text.textContent=product.title+' × '+n+' ';li.append(text);for(const [label,change]of [['−',-1],['+',1]]){const button=document.createElement('button');button.textContent=label;button.setAttribute('aria-label',(change===1?'Increase ':'Decrease ')+product.title);button.onclick=()=>{state.cart[key]=Math.max(0,(state.cart[key]||0)+change);persist();renderCart();};li.append(button);}$('#cart-list').append(li);}$('#cart-total').textContent=quantity+' items · '+new Intl.NumberFormat('en',{style:'currency',currency:'USD'}).format(total);}
document.querySelectorAll('[data-add]').forEach(button=>button.onclick=()=>{const id=button.dataset.add;state.cart[id]=(state.cart[id]||0)+1;persist();renderCart();announce('Added to your cart');});
$('#clear-cart')?.addEventListener('click',()=>{state.cart={};persist();renderCart();});renderCart();
state.saved??=[];
document.querySelectorAll('[data-save]').forEach(button=>{const update=()=>button.textContent=state.saved.includes(button.dataset.save)?'Saved ✓':'Save article';update();button.onclick=()=>{const id=button.dataset.save;state.saved=state.saved.includes(id)?state.saved.filter(x=>x!==id):[...state.saved,id];persist();update();};});
document.querySelectorAll('[data-read]').forEach(button=>button.onclick=()=>{const item=config.items.find(x=>x.id===button.dataset.read);$('#article-title').textContent=item.title;$('#article-body').textContent=item.content;$('#article-dialog').showModal();});$('#close-article')?.addEventListener('click',()=>$('#article-dialog').close());
state.tasks??=[];
function renderTasks(){if(!$('#task-list'))return;$('#task-list').replaceChildren();for(const task of state.tasks){const li=document.createElement('li'),check=document.createElement('input'),label=document.createElement('label'),remove=document.createElement('button');check.type='checkbox';check.checked=task.done;check.onchange=()=>{task.done=check.checked;persist();renderTasks();};label.append(check,document.createTextNode(task.text));if(task.done)label.style.textDecoration='line-through';remove.textContent='Remove';remove.setAttribute('aria-label','Remove '+task.text);remove.onclick=()=>{state.tasks=state.tasks.filter(x=>x.id!==task.id);persist();renderTasks();};li.append(label,remove);$('#task-list').append(li);}$('#task-count').textContent=state.tasks.filter(x=>!x.done).length+' tasks remaining';}
$('#task-form')?.addEventListener('submit',event=>{event.preventDefault();const text=$('#new-task').value.trim();if(!text)return;state.tasks.push({id:crypto.randomUUID(),text,done:false});persist();renderTasks();event.target.reset();});renderTasks();
let seconds=1500,running=false;function timer(){if($('#timer'))$('#timer').textContent=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0');}setInterval(()=>{if(running&&seconds>0){seconds--;timer();if(!seconds){running=false;announce('Focus session complete');}}},1000);$('#start-timer')?.addEventListener('click',()=>{running=!running;$('#start-timer').textContent=running?'Pause':'Start focus';});$('#reset-timer')?.addEventListener('click',()=>{running=false;seconds=1500;timer();$('#start-timer').textContent='Start focus';});
document.querySelectorAll('[data-contact]').forEach(form=>form.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector('button');button.disabled=true;try{if(config.preview){announce('Preview only: no submission was sent. Download and run the project to save submissions.');}else{const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(form)))});const data=await response.json();if(!response.ok)throw Error(data.error);announce('Your submission has been saved. Reference: '+data.id);form.reset();}}catch(error){announce(error.message);}finally{button.disabled=false;}}));
function accountState(id){storageKey='bebin-template-'+config.id+'-'+id;try{state=JSON.parse(localStorage.getItem(storageKey))||{};}catch{state={};}state.tasks??=[];renderTasks();}
document.querySelectorAll('[data-auth]').forEach(form=>form.addEventListener('submit',async event=>{event.preventDefault();if(config.preview){announce('Authentication works in the downloaded project. Preview mode does not create an account.');return;}try{const response=await fetch('/api/'+form.dataset.auth,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(form)))});const data=await response.json();if(!response.ok)throw Error(data.error);accountState(data.id);$('#auth-forms').hidden=true;$('#private-workspace').hidden=false;announce('Signed in as '+data.name);}catch(error){announce(error.message);}}));
$('#template-signout')?.addEventListener('click',async()=>{if(!config.preview)await fetch('/api/logout',{method:'POST'});$('#private-workspace').hidden=true;$('#auth-forms').hidden=false;announce('Signed out');});
if(config.category==='admin'&&!config.preview)fetch('/api/me').then(r=>r.json()).then(d=>{if(d.name){accountState(d.id);$('#auth-forms').hidden=true;$('#private-workspace').hidden=false;}}).catch(()=>{});
$('#assistant-form')?.addEventListener('submit',async event=>{event.preventDefault();const button=event.target.querySelector('button');button.disabled=true;$('#assistant-output').textContent='Thinking…';try{if(config.preview)throw Error('Run the downloaded project and configure GROQ_API_KEY in .env to use the assistant.');const response=await fetch('/api/assistant',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:$('#assistant-prompt').value})});const data=await response.json();if(!response.ok)throw Error(data.error);$('#assistant-output').textContent=data.text;}catch(error){$('#assistant-output').textContent=error.message;}finally{button.disabled=false;}});
